trigger:
- main

pool:
  name: Default  # Using your self-hosted agent

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx1024m'
    tasks: 'build'
