trigger:
- main

pool:
  name: Default   # Or use vmImage: 'ubuntu-latest' if Microsoft-hosted

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: ''        # Leave empty to use installed Gradle
    gradleOptions: '-Xmx1024m'
    tasks: 'build'
