trigger:
- main

pool:
  name: Default   # your self-hosted agent pool name

steps:
- checkout: self

- script: dir
  displayName: 'List repository files'

- script: echo "Running Gradle build"
  displayName: 'Echo Message'

- script: .\gradlew.bat clean build
  displayName: 'Build with Gradle'
