trigger:
- main  # Adjust if your branch is named differently

pool:
  name: 'Azure Pipelines'
  demands:
    - agent.name -equals Hosted Agent

steps:
- task: UseJava@1
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'

- script: |
    echo "Building the project..."
    javac HelloWorld.java
    java HelloWorld
  displayName: 'Build and Run Java Program'
