trigger:
- main

pool:
  name: Default  # Using your self-hosted agent

steps:
- script: |
    echo "Compiling Java file..."
    javac HelloWorld.java
    echo "Running Java program..."
    java HelloWorld
  displayName: 'Compile and Run Java Program'
