trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: Checkout@1

- script: echo Running Gradle build
  displayName: 'Run echo'

- script: gradlew.bat clean build
  displayName: 'Build with Gradle'
