trigger:
- main

pool:
  name: Default  # This must match the pool name where your agent is added

steps:
- checkout: self

- script: echo Running Gradle build
  displayName: 'Echo Message'

- script: gradlew.bat clean build
  displayName: 'Build with Gradle'
