trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self

  - script: |
      echo Running Gradle build
    displayName: 'Run echo'

  - script: |
      ./gradlew clean build
    displayName: 'Build with Gradle'
