trigger:
- main

pool:
  name: Default  # or your agent pool name

steps:
- checkout: self

- script: echo Running Gradle build
  displayName: 'Echo Message'

- script: .\gradlew.bat clean build
  displayName: 'Build with Gradle'
