trigger:
- main

pool:
  name: Default

steps:
- checkout: self

- script: dir
  displayName: 'List files in working directory'

- script: echo "Running Gradle build"
  displayName: 'Echo Message'

- script: .\gradlew.bat clean build
  displayName: 'Build with Gradle'
